style:
  active: true
  WildcardImport:
    active: true
  UnusedImports:
    active: true
  MaxLineLength:
    active: true
    maxLineLength: 140

naming:
  active: false

complexity:
  active: true
  LongMethod:
    active: true
    threshold: 60
  LargeClass:
    active: true
    threshold: 600
  CyclomaticComplexMethod:
    active: true
    threshold: 15

empty-blocks:
  active: true

potential-bugs:
  active: true
  EqualsAlwaysReturnsTrueOrFalse:
    active: true
  UnsafeCast:
    active: true
  UnsafeCallOnNullableType:
    active: true

exceptions:
  active: true
  InstanceOfCheckForException:
    active: true
  ThrowingNewInstanceOfSameException:
    active: true

performance:
  active: true
  ArrayPrimitive:
    active: true
